### ISSUE TITLE
Forgotten Races Boons don't show up in selector

### ISSUE THREAD

**Issue by ThePennitentOne** [benediktwerner/FTL-Multiverse-Judge-Boon-Selector-Mod#1]
Like the title says i have unlocked the forgotten races salt man boon and yet its not showing up in the boon selector.

**Comment by benediktwerner** [comment]
Yeah, unfortunately, there's no simple way to automatically get all the boons, so all the available boons have to be added manually. The "boon from last run" option is kind of an intentional fall-back to the default behavior so it always works correctly.

I'll try to look into adding the Forgotten Races boons when I have some time.

**Comment by benediktwerner** [comment]
Yeah, unfortunately, there's no simple way to automatically get all the boons, so all the available boons have to be added manually. The "boon from last run" option is kind of an intentional fall-back to the default behavior so it always works correctly.

I'll try to look into adding the Forgotten Races boons when I have some time.

**Comment by benediktwerner** [comment]
Yeah, unfortunately, there's no simple way to automatically get all the boons, so all the available boons have to be added manually. The "boon from last run" option is kind of an intentional fall-back to the default behavior so it always works correctly.

I'll try to look into adding the Forgotten Races boons when I have some time.

**Comment by benediktwerner** [comment]
Yeah, unfortunately, there's no simple way to automatically get all the boons, so all the available boons have to be added manually. The "boon from last run" option is kind of an intentional fall-back to the default behavior so it always works correctly.

I'll try to look into adding the Forgotten Races boons when I have some time.

**Comment by benediktwerner** [comment]
The latest version now supports boons from Forgotten Races, Forgotten Diamonds, and Insurrection+ Selection.
